### PR TITLE
Add HUD class and some other changes to classes

### PR DESCRIPTION
**Pull request by BdeBock**

### CODE REVIEW

**Comment by RogierVrooman** [comment]
Looking good! Maybe start with 3 hearts, and be dead when the last heart is gone. That way it seems a bit more logical to me. So the same amount of lives, but show one heart more, if you know what I mean.

**Comment by BdeBock** [comment]
Yeah I agree with you that 3 hearts seems more logical. But I did it this way on purpose because the original Bubble Bobble also did it this way.

**Comment by RogierVrooman** [comment]
Ah OK, explains a lot. Let's see that as a small improvement of Bubble Bobble then! I'd still say go for 3 hearts.

**Comment by BdeBock** [comment]
K I'll fix it

**Comment by BdeBock** [comment]
So uhm I fixed it and committed it, but I dont see the commit appearing...

**Comment by RogierVrooman** [comment]
Yes, looking good! I'd say merge him with the master!

**Pull request merged**
